
name: Relazione

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build documentation
      run: |
        sudo apt-get install texlive-latex-recommended texlive-fonts-recommended texlive-lang-italian texlive-latex-extra -y
        mkdir -p docs_build
        cd docs
        pdflatex -interaction=nonstopmode --output-dir=../docs_build --shell-escape Relazione.tex
        pdflatex -interaction=nonstopmode --output-dir=../docs_build --shell-escape Relazione.tex
